// This file is automatically generated by the Firebase setup process.
// You can edit it if you need to, but it's usually best to let the tooling handle it.

export const firebaseConfig = {
  "projectId": "studio-8019266465-1ccc6",
  "appId": "1:379060175513:web:310946328a9300b9bd2e08",
  "storageBucket": "studio-8019266465-1ccc6.appspot.com",
  "apiKey": "AIzaSyDK1Lh2MgO4r1nmmjpv0Cc0Ihn112DCeeg",
  "authDomain": "studio-8019266465-1ccc6.firebaseapp.com",
  "messagingSenderId": "379060175513",
  "measurementId": "G-5G530E0N3B"
};
