// This file is automatically generated by the Firebase setup process.
// You can edit it if you need to, but it's usually best to let the tooling handle it.

// For local development, these values are hardcoded.
// For production deployment (e.g., on Vercel), you should replace these
// with environment variables. For example:
// apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,

export const firebaseConfig = {
  apiKey: "YOUR_API_KEY",
  authDomain: "YOUR_AUTH_DOMAIN",
  projectId: "YOUR_PROJECT_ID",
  storageBucket: "YOUR_STORAGE_BUCKET",
  messagingSenderId: "YOUR_MESSAGING_SENDER_ID",
  appId: "YOUR_APP_ID",
  measurementId: "YOUR_MEASUREMENT_ID"
};
